export const partnerLogos = [
  '/images/Logo/201-2017471_sub-zero-wolf-or-asko-fridge-oven-or.png.jpeg',
  '/images/Logo/AGT-logo-removebg-preview.png',
  '/images/Logo/Ceilline .png',
  '/images/Logo/Electrolux_logo-removebg-preview.png',
  '/images/Logo/Gazelle-removebg-preview.png',
  '/images/Logo/KD .png',
  '/images/Logo/Kompacplus__2_.png',
  '/images/Logo/Monte .png',
  '/images/Logo/Salice-removebg-preview.png',
  '/images/Logo/Smeg-Logo-removebg-preview.png',
  '/images/Logo/TZ-removebg-preview.png',
  '/images/Logo/Untitled.png-removebg-preview.png',
  '/images/Logo/WhatsApp Image 2026-06-29 at 12.41.46.jpeg',
  '/images/Logo/Yellowstone_-removebg-preview.png',
  '/images/Logo/Yousen .jpg',
  '/images/Logo/alvic-grupo-alvic-removebg-preview.png',
  '/images/Logo/apex-logo.png',
  '/images/Logo/hettich-logo_brandlogos.net_xdyuy.png',
  '/images/Logo/lamitak-removebg-preview.png',
  '/images/Logo/logo-SILESTONE-NegroCosentino-1024x683-removebg-preview.png',
  '/images/Logo/png-transparent-bosch-logo-icon-thumbnail-removebg-preview.png',
  '/images/Logo/png-transparent-hafele-hd-logo-removebg-preview.png',
  '/images/Logo/sub-zero-home-appliance-cooking-ranges-maytag-subzero-refrigerator-repair-png-favpng-BLHztfvFszVHjVA7eknq03tZ6-removebg-preview.png',
  '/images/Logo/スクリーンショット_2023-10-05_171151-removebg-preview.png'
];
